flags: {}
packages:
- '.'
extra-deps:
- Spock-0.9.0.0
- Spock-digestive-0.2.0.0
- hvect-0.3.0.0
- digestive-bootstrap-0.1.0.1
- blaze-bootstrap-0.1.0.1
- reroute-0.3.1.0
- digestive-functors-blaze-0.6.0.6
resolver: lts-3.0
